// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package appserver

type AgentMessageDeltaNotification struct {
	// Delta corresponds to the JSON schema field "delta".
	Delta string `json:"delta"`

	// ItemID corresponds to the JSON schema field "itemId".
	ItemID string `json:"itemId"`

	// ThreadID corresponds to the JSON schema field "threadId".
	ThreadID string `json:"threadId"`

	// TurnID corresponds to the JSON schema field "turnId".
	TurnID string `json:"turnId"`
}

// This translation layer make sure that we expose codex error code in camel case.
//
// When an upstream HTTP status is available (for example, from the Responses API
// or a provider), it is forwarded in `httpStatusCode` on the relevant
// `codexErrorInfo` variant.
type CodexErrorInfo interface{}

// Base64-encoded output chunk emitted for a streaming `command/exec` request.
//
// These notifications are connection-scoped. If the originating connection closes,
// the server terminates the process.
type CommandExecOutputDeltaNotification struct {
	// `true` on the final streamed chunk for a stream when `outputBytesCap` truncated
	// later output on that stream.
	CapReached bool `json:"capReached"`

	// Base64-encoded output bytes.
	DeltaBase64 string `json:"deltaBase64"`

	// Client-supplied, connection-scoped `processId` from the original `command/exec`
	// request.
	ProcessID string `json:"processId"`

	// Output stream for this chunk.
	Stream interface{} `json:"stream"`
}

// Stream label for `command/exec/outputDelta` notifications.
type CommandExecOutputStream interface{}

type CommandExecutionOutputDeltaNotification struct {
	// Delta corresponds to the JSON schema field "delta".
	Delta string `json:"delta"`

	// ItemID corresponds to the JSON schema field "itemId".
	ItemID string `json:"itemId"`

	// ThreadID corresponds to the JSON schema field "threadId".
	ThreadID string `json:"threadId"`

	// TurnID corresponds to the JSON schema field "turnId".
	TurnID string `json:"turnId"`
}

type ErrorNotification struct {
	// Error corresponds to the JSON schema field "error".
	Error TurnError `json:"error"`

	// ThreadID corresponds to the JSON schema field "threadId".
	ThreadID string `json:"threadId"`

	// TurnID corresponds to the JSON schema field "turnId".
	TurnID string `json:"turnId"`

	// WillRetry corresponds to the JSON schema field "willRetry".
	WillRetry bool `json:"willRetry"`
}

type FileChangeOutputDeltaNotification struct {
	// Delta corresponds to the JSON schema field "delta".
	Delta string `json:"delta"`

	// ItemID corresponds to the JSON schema field "itemId".
	ItemID string `json:"itemId"`

	// ThreadID corresponds to the JSON schema field "threadId".
	ThreadID string `json:"threadId"`

	// TurnID corresponds to the JSON schema field "turnId".
	TurnID string `json:"turnId"`
}

type NonSteerableTurnKind string

const NonSteerableTurnKindCompact NonSteerableTurnKind = "compact"
const NonSteerableTurnKindReview NonSteerableTurnKind = "review"

// EXPERIMENTAL - proposed plan streaming deltas for plan items. Clients should not
// assume concatenated deltas match the completed plan item content.
type PlanDeltaNotification struct {
	// Delta corresponds to the JSON schema field "delta".
	Delta string `json:"delta"`

	// ItemID corresponds to the JSON schema field "itemId".
	ItemID string `json:"itemId"`

	// ThreadID corresponds to the JSON schema field "threadId".
	ThreadID string `json:"threadId"`

	// TurnID corresponds to the JSON schema field "turnId".
	TurnID string `json:"turnId"`
}

type ReasoningSummaryPartAddedNotification struct {
	// ItemID corresponds to the JSON schema field "itemId".
	ItemID string `json:"itemId"`

	// SummaryIndex corresponds to the JSON schema field "summaryIndex".
	SummaryIndex int `json:"summaryIndex"`

	// ThreadID corresponds to the JSON schema field "threadId".
	ThreadID string `json:"threadId"`

	// TurnID corresponds to the JSON schema field "turnId".
	TurnID string `json:"turnId"`
}

type ReasoningSummaryTextDeltaNotification struct {
	// Delta corresponds to the JSON schema field "delta".
	Delta string `json:"delta"`

	// ItemID corresponds to the JSON schema field "itemId".
	ItemID string `json:"itemId"`

	// SummaryIndex corresponds to the JSON schema field "summaryIndex".
	SummaryIndex int `json:"summaryIndex"`

	// ThreadID corresponds to the JSON schema field "threadId".
	ThreadID string `json:"threadId"`

	// TurnID corresponds to the JSON schema field "turnId".
	TurnID string `json:"turnId"`
}

type ReasoningTextDeltaNotification struct {
	// ContentIndex corresponds to the JSON schema field "contentIndex".
	ContentIndex int `json:"contentIndex"`

	// Delta corresponds to the JSON schema field "delta".
	Delta string `json:"delta"`

	// ItemID corresponds to the JSON schema field "itemId".
	ItemID string `json:"itemId"`

	// ThreadID corresponds to the JSON schema field "threadId".
	ThreadID string `json:"threadId"`

	// TurnID corresponds to the JSON schema field "turnId".
	TurnID string `json:"turnId"`
}

type ThreadTokenUsage struct {
	// Last corresponds to the JSON schema field "last".
	Last TokenUsageBreakdown `json:"last"`

	// ModelContextWindow corresponds to the JSON schema field "modelContextWindow".
	ModelContextWindow ThreadTokenUsageModelContextWindow `json:"modelContextWindow,omitempty,omitzero"`

	// Total corresponds to the JSON schema field "total".
	Total TokenUsageBreakdown `json:"total"`
}

type ThreadTokenUsageModelContextWindow *int

type ThreadTokenUsageUpdatedNotification struct {
	// ThreadID corresponds to the JSON schema field "threadId".
	ThreadID string `json:"threadId"`

	// TokenUsage corresponds to the JSON schema field "tokenUsage".
	TokenUsage ThreadTokenUsage `json:"tokenUsage"`

	// TurnID corresponds to the JSON schema field "turnId".
	TurnID string `json:"turnId"`
}

type TokenUsageBreakdown struct {
	// CachedInputTokens corresponds to the JSON schema field "cachedInputTokens".
	CachedInputTokens int `json:"cachedInputTokens"`

	// InputTokens corresponds to the JSON schema field "inputTokens".
	InputTokens int `json:"inputTokens"`

	// OutputTokens corresponds to the JSON schema field "outputTokens".
	OutputTokens int `json:"outputTokens"`

	// ReasoningOutputTokens corresponds to the JSON schema field
	// "reasoningOutputTokens".
	ReasoningOutputTokens int `json:"reasoningOutputTokens"`

	// TotalTokens corresponds to the JSON schema field "totalTokens".
	TotalTokens int `json:"totalTokens"`
}

type TurnError struct {
	// AdditionalDetails corresponds to the JSON schema field "additionalDetails".
	AdditionalDetails TurnErrorAdditionalDetails `json:"additionalDetails,omitempty,omitzero"`

	// CodexErrorInfo corresponds to the JSON schema field "codexErrorInfo".
	CodexErrorInfo interface{} `json:"codexErrorInfo,omitempty,omitzero"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`
}

type TurnErrorAdditionalDetails *string
