package exampleutil

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// LastRunSection is one section of the dynamic last-run.md document.
//
// The walkthrough.md (static, hand-maintained, in git) and last-run.md
// (dynamic, regenerated every run, ignored by git) deliberately share the
// same five-section shape so they can be diffed left-to-right when an
// engineer wants to understand whether a divergence is "actual code change"
// or "ambient run-to-run noise".
type LastRunSection struct {
	Title string
	Body  string
}

// WriteLastRunMarkdown writes a five-section last-run.md to path. It creates
// any missing parent directories and overwrites the file on every call.
//
// The header records a UTC timestamp so engineers comparing two runs can tell
// them apart at a glance. The "do not edit by hand" hint is meant for humans
// who stumble onto the file via `git status` (it will not be tracked, but the
// hint discourages confusion).
func WriteLastRunMarkdown(path string, sections []LastRunSection) error {
	if strings.TrimSpace(path) == "" {
		return fmt.Errorf("WriteLastRunMarkdown: empty path")
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("WriteLastRunMarkdown: mkdir %s: %w", filepath.Dir(path), err)
	}

	var sb strings.Builder
	sb.WriteString("<!-- generated by spotlight example; do not edit by hand -->\n")
	fmt.Fprintf(&sb, "# Last run · %s\n\n", time.Now().UTC().Format(time.RFC3339))
	for _, section := range sections {
		title := strings.TrimSpace(section.Title)
		if title == "" {
			continue
		}
		body := strings.TrimRight(section.Body, "\n")
		if body == "" {
			body = "(empty)"
		}
		fmt.Fprintf(&sb, "## %s\n\n%s\n\n", title, body)
	}
	return os.WriteFile(path, []byte(sb.String()), 0o644)
}

// MustWriteLastRunMarkdown is the panic-on-error wrapper used by spotlights.
// last-run.md is a side-effect of running the example; failing to write it
// signals a real environment problem (no disk, no permission), so failing
// loudly is the right default.
func MustWriteLastRunMarkdown(path string, sections []LastRunSection) {
	if err := WriteLastRunMarkdown(path, sections); err != nil {
		Fatalf("write last-run markdown %q: %v", path, err)
	}
}

// FenceCodeBlock wraps the given content in a triple-backtick fenced code
// block tagged with the supplied language (use "" for an untagged fence). It
// is purely a formatting helper for callers building Body strings.
func FenceCodeBlock(language, content string) string {
	language = strings.TrimSpace(language)
	content = strings.TrimRight(content, "\n")
	return "```" + language + "\n" + content + "\n```"
}
